call git clone git://git.apache.org/cordova-amazon-fireos.git
call git clone git://git.apache.org/cordova-android.git
call git clone git://git.apache.org/cordova-app-harness.git
call git clone git://git.apache.org/cordova-app-hello-world.git
call git clone git://git.apache.org/cordova-bada.git
call git clone git://git.apache.org/cordova-blackberry.git
call git clone git://git.apache.org/cordova-browser.git
call git clone git://git.apache.org/cordova-cli.git
call git clone git://git.apache.org/cordova-coho.git
call git clone git://git.apache.org/cordova-docs.git
call git clone git://git.apache.org/cordova-firefoxos.git
call git clone git://git.apache.org/cordova-ios.git
call git clone git://git.apache.org/cordova-js.git
call git clone git://git.apache.org/cordova-labs.git
call git clone git://git.apache.org/cordova-lib.git
call git clone git://git.apache.org/cordova-medic.git
call git clone git://git.apache.org/cordova-mobile-spec.git
call git clone git://git.apache.org/cordova-osx.git
call git clone git://git.apache.org/cordova-plugin-battery-status.git
call git clone git://git.apache.org/cordova-plugin-camera.git
call git clone git://git.apache.org/cordova-plugin-console.git
call git clone git://git.apache.org/cordova-plugin-contacts.git
call git clone git://git.apache.org/cordova-plugin-device-motion.git
call git clone git://git.apache.org/cordova-plugin-device-orientation.git
call git clone git://git.apache.org/cordova-plugin-device.git
call git clone git://git.apache.org/cordova-plugin-dialogs.git
call git clone git://git.apache.org/cordova-plugin-file-transfer.git
call git clone git://git.apache.org/cordova-plugin-file.git
call git clone git://git.apache.org/cordova-plugin-geolocation.git
call git clone git://git.apache.org/cordova-plugin-globalization.git
call git clone git://git.apache.org/cordova-plugin-inappbrowser.git
call git clone git://git.apache.org/cordova-plugin-media-capture.git
call git clone git://git.apache.org/cordova-plugin-media.git
call git clone git://git.apache.org/cordova-plugin-network-information.git
call git clone git://git.apache.org/cordova-plugin-splashscreen.git
call git clone git://git.apache.org/cordova-plugin-statusbar.git
call git clone git://git.apache.org/cordova-plugin-test-framework.git
call git clone git://git.apache.org/cordova-plugin-vibration.git
call git clone git://git.apache.org/cordova-plugins.git
call git clone git://git.apache.org/cordova-plugman.git
call git clone git://git.apache.org/cordova-qt.git
call git clone git://git.apache.org/cordova-registry-web.git
call git clone git://git.apache.org/cordova-registry.git
call git clone git://git.apache.org/cordova-tizen.git
call git clone git://git.apache.org/cordova-ubuntu.git
call git clone git://git.apache.org/cordova-webos.git
call git clone git://git.apache.org/cordova-weinre.git
call git clone git://git.apache.org/cordova-windows.git
call git clone git://git.apache.org/cordova-wp8.git